### PR TITLE
Fix verifiers generation bug on JS projects

### LINKED ISSUE #78: proving or generating verifiers contract throws an error when using Javascript in Hardhat
### hardhat-zkit version

0.5.13

### What happened?

For Hardhat **Javascript** project. After setup and compiling the circuits using `npx hardhat zkit make` and when trying to generate verifiers contract using `npx hardhat zkit verifiers`, I get the following error:
```bash
Starting generation of Solidity verifier contracts...

⠋ Generating Groth16 Solidity verifier contract for Commitment circuitError in plugin @solarity/hardhat-zkit: Undefined or invalid proving system is passed. Please recompile the circuits or change the proving system.
```

Also, in the unit test of [this blog](https://medium.com/@Arvolear/introducing-hardhat-zkit-how-did-you-even-use-circom-before-a7b463a5575b), when trying to generate the proof, the test reverts because of the same above error.

### Minimal reproduction steps

- Init a hardhat project **without typescript(js)** and install the latest zkit version `0.5.13` 
- Reproduce the [steps of the blog post](https://medium.com/@Arvolear/introducing-hardhat-zkit-how-did-you-even-use-circom-before-a7b463a5575b). 
- After compiling the circom circuit,  generate the verifiers contract with `npx hardhat zkit verifiers`, and the above error will be thrown.

### PR DESCRIPTION
**Pull request by Hrom131**
- [x] Since this PR suggests a **bug fix**, the relevant tests have been added.
- [ ] Since this PR introduces a **new feature**, the update has been discussed in an Issue or with the team.
- [ ] This PR is just a **minor change**, like a typo fix.

---

Close #78

### CODE REVIEW

File: test/helpers.ts [hunk 1]
```diff
@@ -12,11 +12,14 @@ export function useEnvironment(
   fixtureProjectName: string,
   withCleanUp: boolean = false,
   withLogging: boolean = true,
+  withTSProject: boolean = true,
   networkName = "hardhat",
```
Comment (Arvolear) [inline test/helpers.ts:16]: Maybe create a typed config for that?

Comment (Hrom131) [reply test/helpers.ts:16]: Yeah, good idea!

Comment (Hrom131) [reply test/helpers.ts]: Done

**Review by Arvolear — APPROVED** [review]
LGTM!
